### ISSUE TITLE
Custom icon

### ISSUE THREAD

**Issue by Mrtn91** [htmlburger/carbon-field-icon#2]
How do i print the class of a custom icon, the output with print_r dosnt show me any array of my custom icon as fontaswesome icons do, what im missing here? the output is the first letter of the name of my custom icon

**Comment by jorostoyanov** [comment]
Hi @Mrtn91,

When using the `carbon_get_*` functions, the result contains an array in which there is a `class` element with the class that you can use for the selected icon.

Given the following field definition:

```
Container::make( 'post_meta', __( 'Post Options' ) )
	->where( 'post_type', '=', 'page' )
	->add_fields( array(
		Field::make( 'icon', 'crb_icon', __( 'Choose Icon' ) ),
        ) );
```

The following call `print_r( carbon_get_the_post_meta( 'crb_icon' ) )` will give you this output:

```
Array
(
    [value] => home
    [name] => home
    [class] => fa fa-home
    [contents] => 
    [categories] => Array
        (
            [0] => Web Application Icons
            [1] => main
            [2] => house
        )
)
```

and then you can do something like:

```
<?php $icon = carbon_get_the_post_meta( 'crb_icon' ); ?>

<i class="<?php echo $icon['class']; ?>"></i>
```

Hope this helps :)
