### ISSUE TITLE
Custom list

### ISSUE THREAD

**Issue by dackr** [htmlburger/carbon-field-icon#4]
I want to load my custom icons, and the question is how can I load my custom icons? The example is how I load the font icon files so you can see in the previous one.
Please give an example of how to put my custom icons all the process thanks.

this is example in this page but not have more information.
'my-custom-icon-2' => array(
                'name'        => 'My Custom Icon 2',
                'id'          => 'my-custom-icon-2',
                'class'       => 'my-custom-prefix-class',
                'contents'    => '&nbsp;',
                'categories'  => array( 'shop', 'checkout', 'product' ),
            ),

**Comment by jorostoyanov** [comment]
Hi @dackr!

V3 is now available which allows you to register custom list of icons.

Check out the "Custom List" section of the README -- https://github.com/htmlburger/carbon-field-icon/blob/master/README.md -- for more information.

If you experience any issues feel free to open a new issue.
