### ISSUE TITLE
v3 support

### ISSUE THREAD

**Issue by ChipRyan** [htmlburger/carbon-field-icon#5]
Hey,

Is this field going to support v3 anytime soon?

**Comment by robinwittebol** [comment]
This is preventing us from upgrading to v3

**Comment by jorostoyanov** [comment]
Hey Guys!

We have just released v3 of the library which adds support for Carbon Fields v3 -- https://github.com/htmlburger/carbon-field-icon/releases/tag/v3.0.0

Cheers 🎉
