### ISSUE TITLE
Bug on Taxonomy screen

### ISSUE THREAD

**Issue by DKudleichuk** [htmlburger/carbon-field-icon#6]
Hi guys! I have found that this extension looks ugly when i add icon field on Taxonomy screen, could you fix that?

Thank you! :)

![Screenshot_1](https://user-images.githubusercontent.com/12991525/57092554-50918b80-6d14-11e9-97c6-e15e515ed5b5.png)

**Comment by DKudleichuk** [comment]
p.s. here is my temporary fix

```
	body.edit-tags-php .cf-icon-search__input {
		width: auto !important;
	}
	body.edit-tags-php .cf-icon-switcher__options-list__item {
		flex: 0 0 33.3333%;
	}
```

**Comment by DKudleichuk** [comment]
Also, some of icons are not displayed (see Dashicons)

![Screenshot_1](https://user-images.githubusercontent.com/12991525/57191585-e5240580-6f2f-11e9-841f-3c8beb7a542d.png)

**Comment by jorostoyanov** [comment]
Hi @DKudleichuk,

The styles have been updated in the latest release - v3.1.0

Regarding the Dashicons problem, I have opened a new issue here -- https://github.com/htmlburger/carbon-field-icon/issues/7

I am closing this ticket.

Thank you for your contribution 🍾
